// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: book.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookService_AddBook_FullMethodName    = "/books.BookService/AddBook"
	BookService_EditBook_FullMethodName   = "/books.BookService/EditBook"
	BookService_DeleteBook_FullMethodName = "/books.BookService/DeleteBook"
	BookService_GetBook_FullMethodName    = "/books.BookService/GetBook"
)

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	AddBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BaseResponseBook, error)
	EditBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BaseResponseBook, error)
	DeleteBook(ctx context.Context, in *BookIdRequest, opts ...grpc.CallOption) (*BaseResponseBook, error)
	GetBook(ctx context.Context, in *BookIdRequest, opts ...grpc.CallOption) (*BaseResponseBook, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) AddBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BaseResponseBook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBook)
	err := c.cc.Invoke(ctx, BookService_AddBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) EditBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BaseResponseBook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBook)
	err := c.cc.Invoke(ctx, BookService_EditBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) DeleteBook(ctx context.Context, in *BookIdRequest, opts ...grpc.CallOption) (*BaseResponseBook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBook)
	err := c.cc.Invoke(ctx, BookService_DeleteBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *BookIdRequest, opts ...grpc.CallOption) (*BaseResponseBook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBook)
	err := c.cc.Invoke(ctx, BookService_GetBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility.
type BookServiceServer interface {
	AddBook(context.Context, *BookRequest) (*BaseResponseBook, error)
	EditBook(context.Context, *BookRequest) (*BaseResponseBook, error)
	DeleteBook(context.Context, *BookIdRequest) (*BaseResponseBook, error)
	GetBook(context.Context, *BookIdRequest) (*BaseResponseBook, error)
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookServiceServer struct{}

func (UnimplementedBookServiceServer) AddBook(context.Context, *BookRequest) (*BaseResponseBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBook not implemented")
}
func (UnimplementedBookServiceServer) EditBook(context.Context, *BookRequest) (*BaseResponseBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditBook not implemented")
}
func (UnimplementedBookServiceServer) DeleteBook(context.Context, *BookIdRequest) (*BaseResponseBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (UnimplementedBookServiceServer) GetBook(context.Context, *BookIdRequest) (*BaseResponseBook, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}
func (UnimplementedBookServiceServer) testEmbeddedByValue()                     {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookService_AddBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).AddBook(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_EditBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).EditBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookService_EditBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).EditBook(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookService_DeleteBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).DeleteBook(ctx, req.(*BookIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookService_GetBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*BookIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "books.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _BookService_AddBook_Handler,
		},
		{
			MethodName: "EditBook",
			Handler:    _BookService_EditBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _BookService_DeleteBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}

const (
	BooksStocksService_AddBooksStocks_FullMethodName    = "/books.BooksStocksService/AddBooksStocks"
	BooksStocksService_EditBooksStocks_FullMethodName   = "/books.BooksStocksService/EditBooksStocks"
	BooksStocksService_DeleteBooksStocks_FullMethodName = "/books.BooksStocksService/DeleteBooksStocks"
	BooksStocksService_GetBooksStocks_FullMethodName    = "/books.BooksStocksService/GetBooksStocks"
)

// BooksStocksServiceClient is the client API for BooksStocksService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BooksStocksServiceClient interface {
	AddBooksStocks(ctx context.Context, in *BooksStocksRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error)
	EditBooksStocks(ctx context.Context, in *BooksStocksRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error)
	DeleteBooksStocks(ctx context.Context, in *BooksStocksIdRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error)
	GetBooksStocks(ctx context.Context, in *BooksStocksIdRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error)
}

type booksStocksServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBooksStocksServiceClient(cc grpc.ClientConnInterface) BooksStocksServiceClient {
	return &booksStocksServiceClient{cc}
}

func (c *booksStocksServiceClient) AddBooksStocks(ctx context.Context, in *BooksStocksRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBookStocks)
	err := c.cc.Invoke(ctx, BooksStocksService_AddBooksStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksStocksServiceClient) EditBooksStocks(ctx context.Context, in *BooksStocksRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBookStocks)
	err := c.cc.Invoke(ctx, BooksStocksService_EditBooksStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksStocksServiceClient) DeleteBooksStocks(ctx context.Context, in *BooksStocksIdRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBookStocks)
	err := c.cc.Invoke(ctx, BooksStocksService_DeleteBooksStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksStocksServiceClient) GetBooksStocks(ctx context.Context, in *BooksStocksIdRequest, opts ...grpc.CallOption) (*BaseResponseBookStocks, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResponseBookStocks)
	err := c.cc.Invoke(ctx, BooksStocksService_GetBooksStocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksStocksServiceServer is the server API for BooksStocksService service.
// All implementations must embed UnimplementedBooksStocksServiceServer
// for forward compatibility.
type BooksStocksServiceServer interface {
	AddBooksStocks(context.Context, *BooksStocksRequest) (*BaseResponseBookStocks, error)
	EditBooksStocks(context.Context, *BooksStocksRequest) (*BaseResponseBookStocks, error)
	DeleteBooksStocks(context.Context, *BooksStocksIdRequest) (*BaseResponseBookStocks, error)
	GetBooksStocks(context.Context, *BooksStocksIdRequest) (*BaseResponseBookStocks, error)
	mustEmbedUnimplementedBooksStocksServiceServer()
}

// UnimplementedBooksStocksServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBooksStocksServiceServer struct{}

func (UnimplementedBooksStocksServiceServer) AddBooksStocks(context.Context, *BooksStocksRequest) (*BaseResponseBookStocks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBooksStocks not implemented")
}
func (UnimplementedBooksStocksServiceServer) EditBooksStocks(context.Context, *BooksStocksRequest) (*BaseResponseBookStocks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditBooksStocks not implemented")
}
func (UnimplementedBooksStocksServiceServer) DeleteBooksStocks(context.Context, *BooksStocksIdRequest) (*BaseResponseBookStocks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBooksStocks not implemented")
}
func (UnimplementedBooksStocksServiceServer) GetBooksStocks(context.Context, *BooksStocksIdRequest) (*BaseResponseBookStocks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooksStocks not implemented")
}
func (UnimplementedBooksStocksServiceServer) mustEmbedUnimplementedBooksStocksServiceServer() {}
func (UnimplementedBooksStocksServiceServer) testEmbeddedByValue()                            {}

// UnsafeBooksStocksServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BooksStocksServiceServer will
// result in compilation errors.
type UnsafeBooksStocksServiceServer interface {
	mustEmbedUnimplementedBooksStocksServiceServer()
}

func RegisterBooksStocksServiceServer(s grpc.ServiceRegistrar, srv BooksStocksServiceServer) {
	// If the following call pancis, it indicates UnimplementedBooksStocksServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BooksStocksService_ServiceDesc, srv)
}

func _BooksStocksService_AddBooksStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksStocksServiceServer).AddBooksStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BooksStocksService_AddBooksStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksStocksServiceServer).AddBooksStocks(ctx, req.(*BooksStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksStocksService_EditBooksStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksStocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksStocksServiceServer).EditBooksStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BooksStocksService_EditBooksStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksStocksServiceServer).EditBooksStocks(ctx, req.(*BooksStocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksStocksService_DeleteBooksStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksStocksIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksStocksServiceServer).DeleteBooksStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BooksStocksService_DeleteBooksStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksStocksServiceServer).DeleteBooksStocks(ctx, req.(*BooksStocksIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BooksStocksService_GetBooksStocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BooksStocksIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksStocksServiceServer).GetBooksStocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BooksStocksService_GetBooksStocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksStocksServiceServer).GetBooksStocks(ctx, req.(*BooksStocksIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BooksStocksService_ServiceDesc is the grpc.ServiceDesc for BooksStocksService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BooksStocksService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "books.BooksStocksService",
	HandlerType: (*BooksStocksServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBooksStocks",
			Handler:    _BooksStocksService_AddBooksStocks_Handler,
		},
		{
			MethodName: "EditBooksStocks",
			Handler:    _BooksStocksService_EditBooksStocks_Handler,
		},
		{
			MethodName: "DeleteBooksStocks",
			Handler:    _BooksStocksService_DeleteBooksStocks_Handler,
		},
		{
			MethodName: "GetBooksStocks",
			Handler:    _BooksStocksService_GetBooksStocks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
